<?php

/**
 * @file
 * Contains sending_messages.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sending_messages_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sending_messages module.
    case 'help.page.sending_messages':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('sending messages') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function sending_messages_theme() {
  return [
    'sending_messages' => [
      'template' => 'sending_messages',
      'render element' => 'children',
    ],
  ];
}
