<?php

/**
 * @file
 * Contains currency_converter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function currency_converter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the currency_converter module.
    case 'help.page.currency_converter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('converter') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function currency_converter_theme() {
  return [
    'currency_converter' => [
      'template' => 'currency_converter',
      'render element' => 'children',
    ],
  ];
}
