<?php

/**
 * @file
 * AJAX Login module file.
 *
 * The module that modifies an existing entry form on the website so that it
 * works without a reboot.
 */

/**
 * Implements form_FORM_ID_alter().
 */
function ajax_login_form_user_login_form_alter(&$form, &$form_state, $form_id) {
/*
  $form = array();

  $form['login'] = array(
    '#type' => 'textfield',
    '#title' => t('Login'),
    '#required' => TRUE,
  );

  $form['password'] = array(
    '#type' => 'password',
    '#title' => t('Password'),
    '#required' => TRUE,
  );

  $form['actions']['#type'] = 'actions';

  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('mySubmit'),
    '#button_type' => 'primary',
  );
*/
  $form['actions']['submit']['#ajax'] = array(
    'callback' => 'ajax_login_form_user_login_callback',
    'wrapper' => 'user-login-form',
    'event' => 'click',
  );
}

/**
 * Function returns form.
 *
 * @return array
 *   It returns a value depending on the state of user authentication.
 */
function ajax_login_form_user_login_callback(&$form, &$form_state, $form_id) {

  //user_login_finalize(Drupal\user\Entity\User::load(UserAuth::authenticate($form_state->getValue('login'), $form_state->getValue('password'))));

  if (\Drupal::currentUser()->isAuthenticated()) {
    $form = array();
    $account = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
    $form['ajax-login'] = array(
      '#markup' => t('Hello, @username! To see the website as a registered user go to this <a href="@user-url">link</a>.', array(
        '@username' => $account->getUsername(),
        '@user-url' => '/user',
      )),
    );
  }

  return $form;
}